### ISSUE TITLE
I am unable to get concentration running

### ISSUE THREAD

**Issue by abhinuvpitale** [timothycrosley/concentration#12]
using Ubuntu 18.04
python2 default

I did a 
```pip3 install concentration```

and then tried 
```sudo concentration improve```

the Error show concentration command not found,

**Comment by bschne** [comment]
I had the same issue on the latest Ubuntu version.

When I tried to uninstall via pip3, I found that the launch script had been place in `/home/[USERNAME]/.local/lib/`, which doesn't see to be in my path for bash.

Manually moving it to /usr/bin fixed it, but I think the installer should be updated to fix this..

**Comment by GreatBahram** [comment]
This is because when you use `sudo`, the PATH environment variable would change a bit and concentration would not be available for root user. You should try this one instead: `sudo $(which concentration)`

**Comment by GreatBahram** [comment]
By the way, it's good idea to install these command line packages by utilizing the [pipx](https://github.com/pipxproject/pipx) project.

**Comment by timothycrosley** [comment]
I've added a note about using concentration with pipx to the README as I think this is a good approach
