### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by jtrakk** [timothycrosley/concentration#13]
There have been [improvements](https://github.com/timothycrosley/concentration/compare/1.1.1...develop) since [the last release in 2016](https://pypi.org/project/concentration/#history). How would you feel about releasing from master?

**Comment by dallasspohn** [comment]
Do you know if there are forks that are still maintained?

**Comment by jtrakk** [comment]
Doesn't look like it https://github.com/timothycrosley/concentration/network/members

**Comment by timothycrosley** [comment]
1.1.2 has been released, sorry for the delay!
