### ISSUE TITLE
How to disable or shorten the waiting time?

### ISSUE THREAD

**Issue by djvdorp** [timothycrosley/concentration#15]
I just updated to the most recent version from a slightly older one when it was first on HN, and now it does this:

```
########################################################################################ARE YOU SURE?########################################################################################
60 seconds to change your mind. Won't you prefer programming? Or a book?
```

I wanted to read the docs for this but the link seems broken? https://timothycrosley.github.io/concentration/

**Comment by timothycrosley** [comment]
Hi! 

Sorry, the documentation website was a work in progress, it should be up now!
I've pushed a new version that allows adding --now if you need a break right away:

`concentration break --now`
