### ISSUE TITLE
SyntaxError: Invalid syntax

### ISSUE THREAD

**Issue by asbjorn** [timothycrosley/concentration#4]
Hi.

I've just install this package through "pip" on my Ubuntu 15.10 laptop. However, I'm getting a "SyntaxError" when trying to run "concentration".

`aa@romeo:~# concentration 
Traceback (most recent call last):
  File "/usr/local/bin/concentration", line 7, in <module>
    from concentration.run import __hug__
  File "/usr/local/lib/python2.7/dist-packages/concentration/run.py", line 65
    def take_break(minutes: hug.types.number=5):
                          ^
SyntaxError: invalid syntax
`
The version pip installed for me was "concentration-1.1.1".

**Comment by timothycrosley** [comment]
Hi @asbjorn,

Concentration requires Python 3.3+, good news is that that should already be installed alongside Python 2.x.x on Ubuntu 15.10, meaning you should be able to simply do:

```
`sudo pip3 install concentration`
```

to resolve your issue. Hopefully this helps, if not let me know if there's anything else I can do.

Thanks!

~Timothy
