### ISSUE TITLE
User file concentration.distractors does not work

### ISSUE THREAD

**Issue by JPFrancoia** [timothycrosley/concentration#5]
Hi,

First, great tool. I needed it.

I just noticed one bug for now. On Manjaro Linux, putting a domain in ~./concentration.distractors has no effect. I ran a `sudo concentration loose` and a `sudo concentration improve` but the domains are still not blocked.

However, putting them in /etc/concentration.distractors worked perfectly.

Just a minor detail, but it's nice to keep config files like that in the user's space.

**Comment by timothycrosley** [comment]
Thanks for reporting! I'll be thinking about how to fix this, I know why it is (concentration is being ran as sudo, so ~ in from it's perspective is root).

**Comment by JPFrancoia** [comment]
Hum I get it :) Good luck to find who called concentration with sudo. If you manage, I'll be glad to know how you did it.
