### ISSUE TITLE
sorry for not understanding how to add the file to the block list

### ISSUE THREAD

**Issue by IrisWEI-1996** [timothycrosley/concentration#6]
My English is poor ,hope I can explain my question clearly.
I am so sorry that I always don't understand how to add the websites which I hope not to be opened when I am working .I have add the URL into the file(new file :/etc/concentration.distractors),but it doesn't work. I wonder the format I need to write in ??    thanks a lot .

**Comment by dallasspohn** [comment]
If you use sudo to run concentration then the `~/.concentration.safe` and `~/.concentration.distractors ` should be in the root home directory.

**Comment by timothycrosley** [comment]
This is fixed in the latest version of concentration to automatically pick up questions in caller of sudo's home directory as well
